const body=document.body,endpoint=body.dataset.endpoint,view=body.dataset.view;
const grid=document.querySelector('#data-grid'),dialog=document.querySelector('#action-dialog');
const text=(value,fallback='-')=>value===undefined||value===null||value===''?fallback:String(value);
const shortTime=value=>value?new Date(value).toISOString().replace('T',' ').slice(0,19):'-';
const cards={
  passes:item=>({title:item.satellite_id||item.id,badge:item.phase,fields:[['Pass',item.id],['Antenna',item.antenna_id],['AOS',shortTime(item.window?.aos)],['LOS',shortTime(item.window?.los)],['Revision',item.window?.revision],['Owner',`${item.owner_station} / ${item.owner_generation}`]]}),
  antennas:item=>({title:item.id,badge:item.mode,fields:[['Owner',item.owner_pass_id||'Available'],['Generation',item.owner_generation],['Azimuth',`${item.azimuth?.toFixed?.(1)||item.azimuth} deg`],['Elevation',`${item.elevation?.toFixed?.(1)||item.elevation} deg`],['Last command',shortTime(item.last_command_at)],['Fault',item.fault_reason||'None']]}),
  rf:item=>({title:item.chain_id,badge:item.transmit_enabled?'TX enabled':'receive safe',fields:[['Pass',item.pass_id],['Center',item.center_hz?`${item.center_hz} Hz`:'Unassigned'],['Doppler',`${item.doppler_hz||0} Hz`],['Polarization',item.polarization],['Inhibit operation',item.inhibit_operation],['Updated',shortTime(item.updated_at)]]}),
  recordings:item=>({title:item.id,badge:item.status,fields:[['Pass',item.pass_id],['Owner',`${item.owner_station} / ${item.owner_generation}`],['Written',item.frames_written],['Buffered',item.frames_buffered],['Started',shortTime(item.started_at)],['Seal reason',item.seal_reason]]})
};
function render(items){grid.innerHTML='';if(!items?.length){grid.innerHTML='<p class="empty">No operational state is available yet.</p>';return}items.forEach(item=>{const model=cards[view](item),node=document.createElement('article');node.className='item';node.innerHTML=`<div class="item-head"><h3>${text(model.title)}</h3><span class="badge">${text(model.badge)}</span></div><dl>${model.fields.map(([k,v])=>`<div><dt>${k}</dt><dd>${text(v)}</dd></div>`).join('')}</dl>`;grid.append(node)})}
async function load(){try{const [data,health]=await Promise.all([fetch(endpoint,{cache:'no-store'}).then(r=>r.json()),fetch('/healthz',{cache:'no-store'}).then(r=>r.json())]);render(data.items||data);document.querySelector('#health-text').textContent='Station online';document.querySelector('#health-dot').style.background='#43bd88';document.querySelector('#metric-time').textContent=new Date(health.now).toISOString().slice(11,19);document.querySelector('#metric-passes').textContent=health.passes;document.querySelector('#metric-antennas').textContent=health.antennas;document.querySelector('#metric-recordings').textContent=health.recordings;document.querySelector('#last-update').textContent=`Updated ${new Date().toISOString().slice(11,19)} UTC`}catch(error){grid.innerHTML=`<p class="empty">Station API unavailable: ${error.message}</p>`;document.querySelector('#health-text').textContent='Station unavailable';document.querySelector('#health-dot').style.background='#b23b36'}}
const forms={passes:[['satellite_id','Satellite ID','SAT-A12'],['antenna_id','Antenna','ANT-01'],['duration_minutes','Duration minutes','8']],rf:[['chain_id','RF chain','RF-01'],['pass_id','Pass ID',''],['center_hz','Center frequency','2245000000']],antennas:[],recordings:[]};
document.querySelector('#primary-action').addEventListener('click',()=>{if(!forms[view].length){load();return}document.querySelector('#dialog-title').textContent=view==='passes'?'Schedule pass':'Apply receive plan';document.querySelector('#dialog-fields').innerHTML=forms[view].map(([id,label,placeholder])=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" name="${id}" placeholder="${placeholder}" required></div>`).join('');document.querySelector('#dialog-error').textContent='';dialog.showModal()});
dialog.addEventListener('close',async()=>{if(dialog.returnValue!=='default')return;const values=Object.fromEntries(new FormData(dialog.querySelector('form')));let target='/api/passes',payload=values;if(view==='passes'){const now=Date.now();payload={satellite_id:values.satellite_id,antenna_id:values.antenna_id,duration_minutes:Number(values.duration_minutes),aos:new Date(now+120000).toISOString()}}else{target=`/api/rf-chains/${values.chain_id}/plan`;payload={pass_id:values.pass_id,center_hz:Number(values.center_hz),doppler_hz:0,polarization:'RHCP'}}try{const response=await fetch(target,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error(await response.text());await load()}catch(error){document.querySelector('#dialog-error').textContent=error.message;dialog.showModal()}});
document.querySelector('#view-description').textContent={passes:'Live pass windows are revision-bound. Extension and acquisition operations share the antenna timeline.',antennas:'Physical pointing and ownership state from the antenna controller.',rf:'Frequency plans, transmit inhibit state and receiver acquisition readiness.',recordings:'Durable frame segments including buffered tail data and seal state.'}[view];
load();setInterval(load,15000);
